apiVersion: v1
kind: Secret
metadata:
    name: mysqlcreds
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:PStMJg==,iv:wwQZFYv9Lb3oLWktkiTLAoDpOmhFknwenLStwq5arpc=,tag:qkcyAoCfchu/Vz865sGDIA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:z573dug=,iv:SxFkkWz4a8FB9t/OaEHldb6ttTm0opDYyParpV2nGl0=,tag:55QUaXM57zLT2MPX0soQ9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-30T19:57:10Z"
    mac: ENC[AES256_GCM,data:kKMafwjSpGwX96kIUZ/bC9Ph3iWveHh313gcmvKBcdOQEmT5lSf0MP1fR1ydDAQqqPobrZk704GiQKVsBK2iUAHoyEhVd6+Iwo7RbQ5/jTYPOKlDQ4IHyREfBOTHinU4T8uuC+5da9BrgcVEv6A2JZoM/dchlqmyq2vQgSGLAHU=,iv:KHx7sYZ6W2WUmOH3KhKdC4TpGUcg+QmonHikT60BXO0=,tag:NglUa+RpxxzerLyAVJ3FXQ==,type:str]
    pgp:
        - created_at: "2023-03-30T19:42:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAwDj+uNXUfoyAQf+OzdPZrqI+sdsUTMT3r5JbbGHEaN+ICpohYQ+R7+gDnFR
            Oqqps3+Dov5bUzCtgsBeVOG9SSYDE0MUj+NIGGEqV8RjB9RO1kKjDKK4C7HN6Zav
            RRs+dSwt+DUBEOMk9TYdGg+Ww8ONqSDE2urcVN9qmehN5AS8PYjlNaiRbYWXuFQt
            XmAFNnjS/+5gAr6+40wVeVSzQfC4owZZU0OMmuywlQCUUksO8ci5iGiw2GPwaYt0
            pZmTXJ1I9aXxt36AcE/T0leJTTTxwhsyBmKAtit4AGA8loq5WBpmVkFz6IMwvyDZ
            6sawKRATZOEUouMEosk9NRKcqZxnzA2Vg/cGmvFMHtJeAb1Qa3p46XleU01gP55c
            sRdNCNX/wRIqOZFVI1avOteyVzmIHWm5bhaZqe5789b30E3kKXQo+/KX8PesjMly
            W08OGI/6Z0NPZuCXIW1V/yiUkJ+h1dYly+ZPzZy2wg==
            =ZyqP
            -----END PGP MESSAGE-----
          fp: 9604B764C432042D6EFE8000A8C8A103A5EFB585
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
